---
- name: Install oh-my-zsh depedencies
  become: true
  apt:
    name={{item}}
    state=latest
    update_cache=yes
  with_items:
    - zsh
    - zsh-syntax-highlighting
  register: ohMyZshInstallation

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: ohMyZshInstallation|success
  register: ohMyZshCloning

- name: Cloning nerd-fonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerd-fonts
    depth: 1
  when: ohMyZshCloning|success
  register: nerdFontsCloning

- name: Install nerd-fonts
  shell: cd /tmp/nerd-fonts && ./install.sh
  when: nerdFontsCloning|success
  register: nerdFontsInstall

- name: Cloning powerlevel9k
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git 
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
  when: nerdFontsInstall|success
  register: powerlevel9kCloning

- name: Configure ~/.zshrc
  template:
    src: ../templates/zshrc.zsh.j2
    dest: ~/.zshrc
  when: powerlevel9kCloning|success
  register: ohMyZshConfiguration

- name: Copy honukai theme
  copy:
    src: ../files/honukai.zsh-theme
    dest: ~/.oh-my-zsh/themes/honukai.zsh-theme
  when: ohMyZshConfiguration|success
  register: ohMyZshSetTheme

- name: Ensures ~/.oh-my-zsh/custom/themes/suriona directory exists
  file: path=~/.oh-my-zsh/custom/themes/suriona state=directory

- name: Install spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
  when: ohMyZshConfiguration|success
  register: ohMyZshInstallSpaceshipTheme

- name: Link {{ nvm.node_version }}
  file: src=~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme  dest=~/.oh-my-zsh/custom/themes/spaceship.zsh-theme state=link
  when: ohMyZshInstallSpaceshipTheme|success
  register: ohMyZshSetSpaceshipTheme

- name: Change your default shell to OhMyZsh
  become: true
  shell : chsh {{ansible_user}} -s $(which zsh)  
  when: ohMyZshSetSpaceshipTheme|success