ZSH_THEME="powerlevel9k/powerlevel9k"
source ~/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme

zsh_node_version() {
	local node_version=$(node -v 2>/dev/null)
	local color="%F{155}"
	local icon="\uE718"
	[[ -z "${node_version}" ]] && return

	if ls *.js >/dev/null 2>&1; then
		echo -n "%{$color%}${icon} v${node_version:1}"
	fi
}

zsh_php_version() {
  	local php_version=$(php -v 2>&1 | grep -oe "^PHP\s*[0-9.]*" | cut -d' ' -f2)
	local color="%F{068}"
	local icon="\ue73d"
  	if [[ -n "$php_version" ]]; then
    	if ls *.php >/dev/null 2>&1; then
			echo -n "%{$color%}${icon} ${php_version}"
		fi
  	fi
}

POWERLEVEL9K_MODE='nerdfont-complete'
DEFAULT_COLOR="252"
DEFAULT_COLOR_INVERTED=none
DEFAULT_BACKGROUND=none

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='red'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='cyan'

POWERLEVEL9K_CUSTOM_NODE_VERSION="zsh_node_version"
POWERLEVEL9K_CUSTOM_NODE_VERSION_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_CUSTOM_NODE_VERSION_FOREGROUND="010"

POWERLEVEL9K_CUSTOM_PHP_VERSION="zsh_php_version"
POWERLEVEL9K_CUSTOM_PHP_VERSION_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_CUSTOM_PHP_VERSION_FOREGROUND="010"

POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR_FOREGROUND="010"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\u2570\U2500$(prompt_time left 1 && prompt_vcs left 2)%F{225}\uF460%F{013}\uF460%F{141}\uF460%F{055}\uF460%f  "

POWERLEVEL9K_USER_ICON="\Uf183\Uf182"
#e771 f0f0 E710 f1fa f188 f182 e722
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="039"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="219"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_FOREGROUND="219"
POWERLEVEL9K_DIR_HOME_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="219"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$DEFAULT_BACKGROUND"

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="009"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="$DEFAULT_BACKGROUND"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="010"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="011"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="219"

POWERLEVEL9K_BATTERY_LOW_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="009"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="010"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="039"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="$DEFAULT_COLOR"

POWERLEVEL9K_STATUS_OK_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_STATUS_OK_FOREGROUND="010"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="009"


POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$DEFAULT_COLOR"

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator user dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time custom_node_version custom_php_version battery)
POWERLEVEL9K_SHOW_CHANGESET=true

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
# /!\ do not use with zsh-autosuggestions

plugins=(k tig gitfast colored-man colorize command-not-found cp dirhistory autojump sudo zsh-syntax-highlighting)
# /!\ zsh-syntax-highlighting and then zsh-autosuggestions must be at the end

source $ZSH/oh-my-zsh.sh

rule () {
	print -Pn '%F{blue}'
	local columns=$(tput cols)
	for ((i=1; i<=columns; i++)); do
	   printf "\u2588"
	done
	print -P '%f'
}
