- name: Install vim depedencies
  become: true
  apt:
    update_cache=yes
    state=latest
    name=vim
  register: vimInstallation

- name: Configure vim
  copy:
    src: ../files/vimrc
    dest: ~/.vimrc
  register: vimConfiguration    
  when: vimInstallation|success

- name: Install spacevim
  shell: curl -sLf https://spacevim.org/install.sh | bash
  when: vimConfiguration|success

